scraper_site:
  image: 'drjova/article-data-codereview'
  ports:
  - "8080:8080"

backend:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code

frontend:
  build: ./react_app
  ports:
  - "3000:3000"
