scraper_site:
  image: 'drjova/article-data-codereview'
  ports:
  - "8080:5000"

backend:
  build: .
  ports:
      - "5555:5555"
  volumes:
   - .:/code

frontend:
  build: ./react_app
  ports:
  - "3000:3000"
